{
 "title": "ArgoCD Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(go_goroutines, namespace)"
   },
   {
    "name": "argocd",
    "query": "label_values(argocd_info, argocd)"
   }
  ]
 },
 "panels": [
  { "title": "Applications", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "content": "![argoimage](https://avatars1.githubusercontent.com/u/30269780?s=120&v=4)"
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds{job=\"$argocd-server-metrics\",namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Total Applications",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(argocd_app_info{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Applications",
   "type": "graph",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(argocd_app_info{namespace=~\"$namespace\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Health Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Healthy",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(argocd_app_info{health_status=\"Healthy\",namespace=~\"$namespace\"} == 1)"
    }
   ]
  },
  {
   "title": "Progressing",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(argocd_app_info{health_status=\"Progressing\",namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Suspended",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(argocd_app_info{health_status=\"Suspended\",namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Degraded",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(argocd_app_info{health_status=\"Degraded\",namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Missing",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(argocd_app_info{health_status=\"Missing\",namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Unknown",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(argocd_app_info{health_status=\"Unknown\",namespace=~\"$namespace\"})"
    }
   ]
  },
  { "title": "Sync Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Synced",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(argocd_app_info{sync_status=\"Synced\",namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "OutOfSync",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(argocd_app_info{sync_status=\"OutOfSync\",namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Unknown",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(argocd_app_info{sync_status=\"Unknown\",namespace=~\"$namespace\"})"
    }
   ]
  },
  { "title": "Controller Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Sync Activity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(changes(argocd_app_sync_total{namespace=~\"$namespace\"}[5m])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Sync Failures",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(changes(argocd_app_sync_total{namespace=~\"$namespace\",phase=~\"Error|Failed\"}[5m])) by (namespace, phase)",
     "legendFormat": "{{namespace}} {{phase}}"
    }
   ]
  },
  {
   "title": "Reconciliation Activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(argocd_app_reconcile_count{namespace=~\"$namespace\"}[10m])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "K8s API Activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(argocd_app_k8s_request_total{namespace=~\"$namespace\"}[5m])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Reconciliation Performance",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(increase(argocd_app_reconcile_bucket{namespace=~\"$namespace\"}[10m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"$argocd-metrics\",namespace=~\"$namespace\"}",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"$argocd-metrics\",namespace=~\"$namespace\"}",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Server Stats:", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"$argocd-server-metrics\",namespace=~\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"$argocd-server-metrics\",namespace=~\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GC Time Quantiles",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=\"$argocd-server-metrics\", quantile=\"1\", namespace=~\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 92 }, "content": "#### gRPC Services:" },
  {
   "title": "grpc service ApplicationService",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_server_handled_total{job=\"$argocd-server-metrics\",grpc_service=\"application.ApplicationService\",namespace=~\"$namespace\"} > 0",
     "legendFormat": "{{grpc_code}},{{grpc_method}}"
    }
   ]
  },
  {
   "title": "grpc service ClusterService",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_server_handled_total{job=\"$argocd-server-metrics\",grpc_service=\"cluster.ClusterService\",namespace=~\"$namespace\"} > 0",
     "legendFormat": "{{grpc_code}},{{grpc_method}}"
    }
   ]
  },
  {
   "title": "grpc service ProjectService",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_server_handled_total{job=\"$argocd-server-metrics\",grpc_service=\"project.ProjectService\",namespace=~\"$namespace\"} > 0",
     "legendFormat": "{{grpc_code}},{{grpc_method}}"
    }
   ]
  },
  {
   "title": "grpc service RepositoryService",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 103 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_server_handled_total{job=\"$argocd-server-metrics\",grpc_service=\"repository.RepositoryService\",namespace=~\"$namespace\"} > 0",
     "legendFormat": "{{grpc_code}},{{grpc_method}}"
    }
   ]
  },
  {
   "title": "grpc service SessionService",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 112 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_server_handled_total{job=\"$argocd-server-metrics\",grpc_service=\"session.SessionService\",namespace=~\"$namespace\"} > 0",
     "legendFormat": "{{grpc_code}},{{grpc_method}}"
    }
   ]
  },
  {
   "title": "grpc service VersionService",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 112 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_server_handled_total{job=\"$argocd-server-metrics\",grpc_service=\"version.VersionService\",namespace=~\"$namespace\"} > 0",
     "legendFormat": "{{grpc_code}},{{grpc_method}}"
    }
   ]
  },
  {
   "title": "grpc service AccountService",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 121 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_server_handled_total{job=\"$argocd-server-metrics\",grpc_service=\"account.AccountService\",namespace=~\"$namespace\"} >1",
     "legendFormat": "{{grpc_code}},{{grpc_method}}"
    }
   ]
  },
  { "title": "Repo Server Stats:", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 130 } },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 131 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"$argocd-repo-server\",namespace=~\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 139 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"$argocd-repo-server\",namespace=~\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Git Requests (ls-remote)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 148 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(argocd_git_request_total{request_type=\"ls-remote\", namespace=~\"$namespace\"}[10m])) by (namespace)"
    }
   ]
  },
  {
   "title": "Git Requests (checkout)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 148 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(argocd_git_request_total{request_type=\"fetch\", namespace=~\"$namespace\"}[10m])) by (namespace)"
    }
   ]
  }
 ]
}